version: '3'
services:
  swapi-movies:
    build: .
    ports:
      - "6000:6000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: star_wars
      MYSQL_USER: root
      MYSQL_PASSWORD: example

    