version: '3'
services:
  swapi-movies:
    build: .
    depends_on:
      - db
    ports:
      - "6000:6000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:

    